### ISSUE TITLE
Expose iRods group home folder to group members

### ISSUE THREAD

**Issue by technics3** [cyverse/sftpgo-deploy#3]
When a group is created in iRods, a home folder is created in `/devZone/home/<groupName>`.

We need to expose this home to group members in STFPGo. Does this feature exist at the moment ?
 
Thanks.

**Comment by iychoi** [comment]
The requested feature is not for this repository. Mounting folders in SFTP is handled by `sftpgo-auth-irods` module when it authenticates iRODS users. Currently, the module creates only two folders, user's home folder and shared folder `/zone/home/shared (or public)`. CyVerse currently do not have any use cases for mounting group folders, so I cannot prioritize working on it. 

If you plan to work on the feature, check the following line to mount the group folder.

https://github.com/cyverse/sftpgo-auth-irods/blob/main/cmd/main.go#L191

You will need to obtain group memberships of the user and find folders created then, add it to `mountPaths` array so that `auth.MakeSFTPGoUser` call creates the folders (following line).

https://github.com/cyverse/sftpgo-auth-irods/blob/main/cmd/main.go#L221

Thanks.

**Comment by technics3** [comment]
Thanks a lot for the tracks, i'll look into that and maybe submit the feature to `sftpgo-auth-irods`.
